on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Install Ruff
        run: python -m pip install --upgrade pip ruff

      - name: Lint with Ruff
        run: poetry run ruff check .
        continue-on-error: false

      - name: Install Test Dependencies
        run: python -m pip install pytest pytest-cov

      - name: Run Unit Tests
        run: poetry run pytest --cov-report term-missing --cov=lambda_app/ tests/
        continue-on-error: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t lambda-ci-image .

      - name: Run Docker Container
        run: docker run -d -p 3001:8080 --name lambda-container lambda-ci-image

      - name: Wait for Lambda to Start
        run: sleep 6

      - name: Verify Container is Running
        run: docker ps

      - name: Test Lambda Function with curl
        run: |
          curl -d @events/event.json http://localhost:3001/2015-03-31/functions/function/invocations | tee lambda-response.json